      SUBROUTINE UVARM(UVAR,DIRECT,T,TIME,DTIME,CMNAME,ORNAME,
     1 NUVARM,NOEL,NPT,LAYER,KSPT,KSTEP,KINC,NDI,NSHR,COORD,
     2 JMAC,JMATYP,MATLAYO,LACCFLA) 
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME,ORNAME
      CHARACTER*3 FLGRAY(15)
      DIMENSION UVAR(NUVARM),DIRECT(3,3),T(3,3),TIME(2)!, DG(5)
      DIMENSION ARRAY(15),JARRAY(15),JMAC(*),JMATYP(*),COORD(*)

C deforamtion gradient tensor:
		CALL GETVRM('DG',ARRAY,JARRAY,FLGRAY,JRCD,JMAC,JMATYP,
     1 		MATLAYO,LACCFLA)
		UVAR(1) = ARRAY(1)
		UVAR(2) = ARRAY(4)
		UVAR(3) = ARRAY(7)
		UVAR(4) = ARRAY(2)
		UVAR(5) = ARRAY(3)
      RETURN
      END
      
       SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     & RPL,DDSDDT,DRPLDE,DRPLDT,
     & STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     & NDI,NSHR,NTENS,NSTATEV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     & CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C 
	INCLUDE 'ABA_PARAM.INC'
C 
      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS),STATEV(NSTATEV),
     & DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     & STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     & PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
C      LOCAL ARRAYS
c
c
      STRESS=0.d0
      DDSDDE=0.d0
c
       WRITE(*,'(A7,A1,I4,A1,I8,A1,I2,A1,E25.15,A1,E25.
     &15,A1,E25.15,A1,E25.15,A1,E25.15,A1,E25.15,A1,E25.15)') 
     1                CMNAME,';',KINC,';',NOEL-1,';',NPT,';', 
     2 				  COORDS(1),';',COORDS(2),';',DFGRD1(1,1),';',
     3                DFGRD1(1,2),';',DFGRD1(2,1),';',DFGRD1(2,2),';'
     4				 ,DFGRD1(3,3)
c
      RETURN
      END
